import { Flower } from "../interfaces/interfaces";

export const flowers: Flower[] = [
  {
    id: 1,
    name: "Margarita",
    binomialName: "Margarita-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-1.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 2,
    name: "Petunia",
    binomialName: "Petunia-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-2.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 3,
    name: "Tulipán",
    binomialName: "Tulipán-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-3.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 4,
    name: "Rosa",
    binomialName: "Rosa-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-4.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 5,
    name: "Margarita",
    binomialName: "Margarita-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-5.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 6,
    name: "Petunia",
    binomialName: "Petunia-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-6.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 7,
    name: "Tulipán",
    binomialName: "Tulipán-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-7.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 8,
    name: "Rosa",
    binomialName: "Rosa-B",
    price: 10,
    imgUrl: "assets/img/flowers/flower-8.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
];
