import { Flower } from "../interfaces/interfaces";

export const flowers: Flower[] = [
  {
    id: 1,
    name: "Margarita",
    binomialName: "Margarita-B",
    price: 10,
    imgUrl: "/assets/img/flowers/1.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 2,
    name: "Petunia",
    binomialName: "Petunia-B",
    price: 10,
    imgUrl: "/assets/img/flowers/2.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 3,
    name: "Tulipán",
    binomialName: "Tulipán-B",
    price: 10,
    imgUrl: "/assets/img/flowers/3.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 4,
    name: "Rosa",
    binomialName: "Rosa-B",
    price: 10,
    imgUrl: "/assets/img/flowers/4.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 5,
    name: "Margarita",
    binomialName: "Margarita-B",
    price: 10,
    imgUrl: "/assets/img/flowers/5.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 6,
    name: "Petunia",
    binomialName: "Petunia-B",
    price: 10,
    imgUrl: "/assets/img/flowers/6.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 7,
    name: "Tulipán",
    binomialName: "Tulipán-B",
    price: 10,
    imgUrl: "/assets/img/flowers/7.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 8,
    name: "Rosa",
    binomialName: "Rosa-B",
    price: 10,
    imgUrl: "/assets/img/flowers/8.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
];
