import { IFlower } from "../interfaces/interfaces";

export const flowers: IFlower[] = [
  {
    id: 1,
    name: "Rosa silvestre",
    binomialName: "Rosales silvestres",
    price: 19.95,
    imgUrl: "/assets/img/flowers/1.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 2,
    name: "Tulipán",
    binomialName: "Tulipa gesneriana",
    price: 24.95,
    imgUrl: "/assets/img/flowers/2.png",
    wateringsPerWeek: 2,
    fertilizerType: "phosphorus",
    heightInCm: 7,
  },
  {
    id: 3,
    name: "Petunia",
    binomialName: "Petunia integrifolia",
    price: 22.95,
    imgUrl: "/assets/img/flowers/3.png",
    wateringsPerWeek: 1,
    fertilizerType: "nitrogen",
    heightInCm: 7,
  },
  {
    id: 4,
    name: "Rosa Grandiflora",
    binomialName: "Rosales grandiflora",
    price: 29.95,
    imgUrl: "/assets/img/flowers/4.png",
    wateringsPerWeek: 4,
    fertilizerType: "phosphorus",
    heightInCm: 8,
  },
  {
    id: 5,
    name: "Margarita",
    binomialName: "Bellis perennis",
    price: 10.95,
    imgUrl: "/assets/img/flowers/5.png",
    wateringsPerWeek: 14,
    fertilizerType: "phosphorus",
    heightInCm: 13,
  },
  {
    id: 6,
    name: "Lirio",
    binomialName: "Lilium candidum",
    price: 17.95,
    imgUrl: "/assets/img/flowers/6.png",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 11,
  },
  {
    id: 7,
    name: "Hortensia",
    binomialName: "Hydrangea",
    price: 24.95,
    imgUrl: "/assets/img/flowers/7.png",
    wateringsPerWeek: 2,
    fertilizerType: "phosphorus",
    heightInCm: 9,
  },
  {
    id: 8,
    name: "Dalia",
    binomialName: "Dahlia",
    price: 34.95,
    imgUrl: "/assets/img/flowers/8.png",
    wateringsPerWeek: 1,
    fertilizerType: "nitrogen",
    heightInCm: 9,
  },
];

export const FLOWER_FERTILIZER_TYPES: any = {
  nitrogen: "Nitrogenado",
  phosphorus: "Fosforado",
};
