import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

type FertilizerType = "nitrogen" | "phosphorus";

interface Flower {
  id: number;
  name: string;
  binomialName: string;
  price: number;
  imgUrl: string;
  wateringsPerWeek: number;
  fertilizerType: FertilizerType;
  heightInCm: number;
}

const flowers: Flower[] = [
  {
    id: 1,
    name: "Margarita",
    binomialName: "Margarita-B",
    price: 10,
    imgUrl:
      "https://www.jardineriaon.com/wp-content/uploads/2017/07/flor-de-margarita-830x551.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 2,
    name: "Petunia",
    binomialName: "Petunia-B",
    price: 10,
    imgUrl:
      "https://laregaderaverde.com/wp-content/uploads/2020/03/Caracter%C3%ADsticas-de-las-petunias.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 3,
    name: "Tulipán",
    binomialName: "Tulipán-B",
    price: 10,
    imgUrl:
      "https://www.jardineriaon.com/wp-content/uploads/2017/07/flor-de-margarita-830x551.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
  {
    id: 4,
    name: "Rosa",
    binomialName: "Rosa-B",
    price: 10,
    imgUrl:
      "https://laregaderaverde.com/wp-content/uploads/2020/03/Caracter%C3%ADsticas-de-las-petunias.jpg",
    wateringsPerWeek: 7,
    fertilizerType: "nitrogen",
    heightInCm: 10,
  },
];

const Home: NextPage = () => {
  const [inputText, setInputText] = useState<string>("");

  const handleInputChange = (event: any) => {
    setInputText(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>🌸 Sweet Petals 🌸</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.inputContainer}>
          <input
            placeholder="Comienza a escribir para buscar..."
            className={styles.input}
            onChange={handleInputChange}
          ></input>
        </div>
        <section className={styles.section}>
          {flowers
            .filter((flower) => {
              return flower.name
                .toLowerCase()
                .includes(inputText.toLowerCase());
            })
            .map((flower: Flower) => {
              return (
                <article className={styles.article}>
                  <img src={flower.imgUrl} className={styles.articleImg}></img>
                  <div className={styles.articleBody}>{flower.name}</div>
                </article>
              );
            })}
        </section>
      </main>
    </div>
  );
};

export default Home;
