import styles from "../styles/Home.module.css";
import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header/Header";

import { Flower } from "../interfaces/interfaces";
import { flowers } from "../resources/flowers";

const Home: NextPage = ({ flowers }: any) => {
  const [inputText, setInputText] = useState<string>("");

  const handleInputChange = (event: any) => {
    setInputText(event.target.value);
  };

  return (
    <>
      <Head>
        <title>🌸 Sweet Petals 🌸</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <div className={styles.inputContainer}>
          <input
            placeholder="Comienza a escribir para buscar..."
            className={styles.input}
            onChange={handleInputChange}
          ></input>
        </div>
        <section className={styles.section}>
          {flowers
            .filter((flower: Flower) => {
              return flower.name
                .toLowerCase()
                .includes(inputText.toLowerCase());
            })
            .map((flower: Flower) => {
              return (
                <Link key={flower.id} href={`/details/${flower.id}`}>
                  <article className={styles.article}>
                    <div className={styles.articleImgContainer}>
                      <img
                        src={flower.imgUrl}
                        alt={flower.name}
                        className={styles.articleImg}
                      ></img>
                    </div>
                    <div className={styles.articleBody}>{flower.name}</div>
                  </article>
                </Link>
              );
            })}
        </section>
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  return { flowers: flowers };
};

export default Home;
